# Generated by Django 4.1.3 on 2022-12-02 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='img',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='desc',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='title',
        ),
    ]
