# Generated by Django 4.1.3 on 2022-12-05 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_rename_img_person_photo_rename_desc_person_profile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fruit',
        ),
    ]
